### ISSUE TITLE
A new question about data download

### ISSUE THREAD

**Issue by syin3** [liyaguang/DCRNN#11]
Hi Yaguang, I read through your answer in Issue#10, in which you said the url is linked to the raw data. I looked into the data and they are of the 207 stations you selected. 

If I want to select the detectors and download data that I want, do you know where is the **original raw data of METR-LA** are? Does this require any form of authorization for the dataset, or is it an open one?

Thx.

**Comment by liyaguang** [comment]
Hi syin3, sorry for the late reply. The raw data is from METRANS LA, and we haven't got permission to share the raw data. For related transportation data, you may refer to http://pems.dot.ca.gov/.
