### ISSUE TITLE
Question on dcrnn_cell

### ISSUE THREAD

**Issue by FrancesZhou** [liyaguang/DCRNN#13]
Hi, Yaguang

I have read through dcrnn codes and there is a little question I cannot understand. I hope for your help.
When the filter type is random walk or dual random walk, why is there a **transpose** operation after calculated random_walk_matrix? 
Actually, in your paper, the defined diffusion convolution is just like graph convolution which does not have the transpose operation after calculated scaled_laplacian_matrix in the code.

**Comment by liyaguang** [comment]
Hi Frances,
Sorry for the late reply. You may refer to Equation (2) for the corresponding explanation in Section 2.2 of the paper. 
Here is a quick screenshot.
![image](https://user-images.githubusercontent.com/5539617/50785419-6a8af800-1265-11e9-8c1f-58cbf2e51f8c.png)
