### ISSUE TITLE
What is the meaning of the last dimension of the input (Batch_size, Time granularity, Node number,2) of the network?

### ISSUE THREAD

**Issue by zhengxuyu** [liyaguang/DCRNN#19]
Hi, where can I get the introduction of the METR-LA and the PEMS-Bay dataset? What is the meaning of the last dimension of the input (Batch_size, Time granularity, Node number,2) of the network?

**Comment by liyaguang** [comment]
Hi zhengxu, the input data is (N x T x V x D), where N is the number of training examples, T corresponds to the number of input steps, V denotes the number of nodes, and D represents the input feature dimension, here 2 consists of 1) the speed and 2) the time.

**Comment by zhengxuyu** [comment]
About the second dim, what 'the time' means to be specific?

**Comment by yansicing** [comment]
The second dimension `T` is `timesteps`, which means `seq_len`, whose value is `12`
The last dimension `D`  is the `speed` corresponding to a certain `time` ~

**Comment by mengmeng716** [comment]
Hi, liyaguang @liyaguang thanks for sharing the great work. actually I don't think the second input feature dimensions is time. because I find the value is something like float in In scientific counting, the value is between [0,1] , mean value 0.497, max value 0.997, min value 0; so can you provide some evidence for the second feature dimenson please?  

thanks and best regards,

**Comment by chenz97** [comment]
Hi @yansicing , thanks for your explaination, but I still have questions here. You said "D is the `speed` corresponding to a certain `time`", and I'm wondering which `time` it is. I was thinking the authors were using 5-minutes average speed, right? If so, what is the `time` that the `speed` corresponds to? Thank you very much!

**Comment by liyaguang** [comment]
Hi @chenz97,  @mengmeng716,  the time dimension refers to the normalized time in a day, e.g., 0:00 am will be 0, while 12pm will be 0.5.

**Comment by chenz97** [comment]
Hi @liyaguang , I got it. Thanks a lot.
