### ISSUE TITLE
Missing distances file PEMS-BAY

### ISSUE THREAD

**Issue by CVxTz** [liyaguang/DCRNN#21]
Hello,

Is there any way I can get the equivalent of "distances_la_2012.csv" but for PEMS-BAY ? 

Best,

**Comment by lisiyu55** [comment]
> Hello,
> 
> Is there any way I can get the equivalent of "distances_la_2012.csv" but for PEMS-BAY ?
> 
> Best,

hi，Have you got this data yet?

**Comment by CVxTz** [comment]
I don't even remember its been so long.

**Comment by liyaguang** [comment]
Sorry for the super late reply. The distance file for PEMS-BAY is available at: [`data/sensor_graph/distances_bay_2017.csv`](https://github.com/liyaguang/DCRNN/blob/master/data/sensor_graph/distances_bay_2017.csv).
