### ISSUE TITLE
Question about the graph convolution kernel

### ISSUE THREAD

**Issue by XianglongTan** [liyaguang/DCRNN#27]
Hi Liyaguang, I have a question about your graph convolution kernel. You compute the diffusion convolution kernel by iteratively doing `x2 = 2*tf.sparse_tensor_dense_matmul(support, x1) - x0`. But, if I am correct, should it be doing `x2 = tf.sparse_tensor_dense_matmul(support, x1)` according to your article?

**Comment by liyaguang** [comment]
HI Xianglong, 
Thanks for your interest in the paper. This part is for the approximation of the diffusion convolution using the Chebyshev polynomial basis which makes the gradient more stable.  Similar results can be achieved even without the Cheyshev polynomial.
