### ISSUE TITLE
Question on Baseline Models

### ISSUE THREAD

**Issue by prateikarora** [liyaguang/DCRNN#28]
In the baseline models that you implemented(specifically ARIMA, SVR and HA); were they trained solely on the temporal data or the entire spatio-temporal data?

**Comment by liyaguang** [comment]
For ARIMA and SVR, each sensor has its own dedicated model, as the classical implementation does not support multivariate time series.
For HA, training is not required, as we just average the traffic speed over the last few weeks.

**Comment by prateikarora** [comment]
@liyaguang could you share the code for the same?

**Comment by prateikarora** [comment]
@liyaguang how did you incorporate the spatial information in ARIMA and SVR model for each sensor?

**Comment by liyaguang** [comment]
For modeling spatial information, you may consider Vector ARIMA (VARIMA) model, or use the simpler Vector Auto-regressive (VAR) model.
