### ISSUE TITLE
Small graphs?

### ISSUE THREAD

**Issue by bkj** [liyaguang/DCRNN#3]
Hi -- It seems like you process the entire graph at each minibatch, which will long the size of the graphs you can apply these methods to. Have you ever worked on methods for operating on subsets of the graph rather than the whole thing?

EDIT: Since you do a graph convolution at each step of the GRU, the receptive field for each node is all of it's 12 hop neighbors.  The diameter of the graph is only 13, so making a prediction for a single node requires touching the entire graph.  Does that sound right?

**Comment by liyaguang** [comment]
> Q1: "Have you ever worked on methods for operating on subsets of the graph rather than the whole thing?"

For this work, we have only implemented the whole graph training mechanism. For subgraph based method, one possible way is to integrate [node sampling](https://openreview.net/forum?id=rytstxWAW&noteId=ByU9EpGSf) in the current framework.

> Q2: "so making a prediction for a single node requires touching the entire graph. Does that sound right?"

The receptive field is mainly affected by the [max_diffusion_step](https://github.com/liyaguang/DCRNN/blob/master/model/dcrnn_model.py#L18), which is usually small, e.g., 2.

**Comment by bkj** [comment]
Makes sense for Q1.

For Q2 -- aggregating features from nodes up to `max_diffusion_step` away happens at each of `seq_len` GRU steps, right?  So if `max_diffusion_step=2` and `seq_len=12`, then the last step of the GRU depends on features of nodes that are 13 hops away, I think.

Related -- how are you forming the adjacency matrix?  I would've expected each node to have degree of 2-3 (attached to nodes up and down the same road), but the nodes have average degree ~ 10.

**Comment by liyaguang** [comment]
> Q2: then the last step of the GRU depends on features of nodes that are 13 hops away, I think.

Yes, in theory, the receptive field can be as large as 13 hops away, but the effect usually decreases exponentially with the increase of hops (because of the RNN). Besides, in extreme case, it is possible that the future traffic of a road depends on the traffic condition 1 hour ago in some far (13 hops) away roads.

> Q3: Related -- how are you forming the adjacency matrix? I would've expected each node to have degree of 2-3 (attached to nodes up and down the same road), but the nodes have average degree ~ 10.

The details about graph construction is available in Appendix E1, and the code is available at https://github.com/liyaguang/DCRNN/blob/master/gen_adj_mx.py#L22

**Comment by bkj** [comment]
Q2 -- Yes understood that the effect decreases exponentially, but unfortunately we still have to touch the 13 hop neighbors.  I'd be interested in doing an experiment where we fix `horizon=12` and vary `seq_len` from ~ 2 to 12.  It may be that (empirically) you don't need to consider neighbors as far removed as you're doing.

Q3 -- So looks like you just make an edge between sensors that are sufficiently close together? 

~ Ben
