### ISSUE TITLE
graph_sensor_locations.csv for PEMS-BAY

### ISSUE THREAD

**Issue by shawnwan47** [liyaguang/DCRNN#30]
can you provide the graph graph_sensor_locations.csv dataset for PEMS-BAY dataset?

**Comment by ChangoLin** [comment]
+1

**Comment by LongWeiZJU** [comment]
+1

**Comment by hammad001** [comment]
+1. Also, how do you make the [from, to, distance] file. I have the station metadata from the pems site. But how to make out which station is connected to which station?

**Comment by liyaguang** [comment]
Sorry for the super late reply. The corresponding file has been added in [`data/sensor_graph/graph_sensor_locations_bay.csv`](https://github.com/liyaguang/DCRNN/blob/master/data/sensor_graph/graph_sensor_locations_bay.csv).  The distance file has been added in [`data/sensor_graph/distances_bay_2017.csv`](https://github.com/liyaguang/DCRNN/blob/master/data/sensor_graph/distances_bay_2017.csv).
