### ISSUE TITLE
question about the metr_la data

### ISSUE THREAD

**Issue by ywgoout** [liyaguang/DCRNN#31]
excuse me    why  there  have  so many  zero  in the  speed  record？

**Comment by liyaguang** [comment]
Zeros generally mean missing data or there is no car being detected during the corresponding time window.

**Comment by RobinLu1209** [comment]
Hi! I also find there are many zero in data and what's your solution to these missing data? Thanks.

**Comment by liyaguang** [comment]
Hi @RobinLu1209 , those missing data will be ignored when calculating the loss. Additionally, you may do missing data imputation, mask to deal with it.
