### ISSUE TITLE
Biases in GRU

### ISSUE THREAD

**Issue by MUCDK** [liyaguang/DCRNN#32]
Hi,

thanks for your great paper!
In Chapter 2.3 you add a bias vector to the convolution for the update/reset/candidate gates, i.e. it seems like the biases are of shape (num_nodes) for every unit, hence in total num_nodes * rnn_units. In your code in dcrnn_cell.py, when adding the biases, this is only of the output_size which is equal to the number of rnn_units for the candidate gate or equal to 2*rnn_units for the reset/update gate. Hence, for every unit only one bias term is added.

Can you please help me with this issue?

Thank you very much.

**Comment by liyaguang** [comment]
About adding bias:
- The bias for reset/update gates are added here: https://github.com/liyaguang/DCRNN/blob/master/model/dcrnn_cell.py#L94
- The bias for the cell is added here: https://github.com/liyaguang/DCRNN/blob/master/model/dcrnn_cell.py#L100

You may seen the [tensorflow implementation](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/ops/rnn_cell_impl.py#L578) for GRU for more information.
