### ISSUE TITLE
dcrnn_train.py : Found Inf or NaN global norm: Tensor had NaN values

### ISSUE THREAD

**Issue by Cancerman-Mylo** [liyaguang/DCRNN#35]
hello , I get an InvalidArgumentError when running dcrnn_train.py, it shows:
![에러](https://user-images.githubusercontent.com/29014695/60393013-5e636180-9b49-11e9-99ce-d64e0cee5bb6.PNG)
when I google it, someone said use smaller batch size but it doesn't work.
what do you think the error happens ?

**Comment by liyaguang** [comment]
I have not come this error. Are you using a new dataset? Can you try to comment the line, i.e., 
`grads, _ = tf.clip_by_global_norm(grads, max_grad_norm)`  which is not essential to the training.
