### ISSUE TITLE
mask loss

### ISSUE THREAD

**Issue by ICDI0906** [liyaguang/DCRNN#37]
Hello~, I have some questions about the mask operation. Why do you mask the loss when training? Is it fair?

**Comment by simmonssong** [comment]
Hi, I have another question about the using of mask loss in this model. 'Mask loss' trick is for **aligning sentence vector**. But time sequence length of output tensor is fixed ? So it is just for **aligning last training/validating/testing sample** ?

**Comment by liyaguang** [comment]
> Hello~, I have some questions about the mask operation. Why do you mask the loss when training? Is it fair?

The mask is used to ignore missing data (indicated by zeros).

**Comment by liyaguang** [comment]
> Hi, I have another question about the using of mask loss in this model. 'Mask loss' trick is for **aligning sentence vector**. But time sequence length of output tensor is fixed ? So it is just for **aligning last training/validating/testing sample** ?

In this task, the mask is used to ignore missing data (indicated by zeros) rather than aligning samples.

**Comment by ICDI0906** [comment]
> > Hi, I have another question about the using of mask loss in this model. 'Mask loss' trick is for **aligning sentence vector**. But time sequence length of output tensor is fixed ? So it is just for **aligning last training/validating/testing sample** ?
> 
> In this task, the mask is used to ignore missing data (indicated by zeros) rather than aligning samples.

Thank you for your timely reply! but if there actually exists zeros values, how to distinguish them

**Comment by simmonssong** [comment]
> In this task, the mask is used to ignore missing data (indicated by zeros) rather than aligning samples.

That refers to original data missed by sensor ?

**Comment by liyaguang** [comment]
@SqySimmon , yes, the mask is used to ignore missing data from sensors.
