### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by pbalapra** [liyaguang/DCRNN#4]
Hi,
>python dcrnn_train.py --config_filename=data/model/dcrnn_config.yaml
FileNotFoundError: File data/df_highway_2012_4mon_sample.h5 does not exist
Could you please upload the missing file.

**Comment by liyaguang** [comment]
Hi Balaprakash,
You can download the file following instructions in ReadMe.

**Comment by bran170294** [comment]
Hello i try to do this part "Train Model"
and i found some error message said ::

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MA008-016839\\data\\model\\info.log'

so does it need .info.log file? 
![image](https://user-images.githubusercontent.com/39514039/43049832-0e2958ee-8e31-11e8-81e0-4fb9d0532150.png)

thanks before ...

**Comment by pbalapra** [comment]
My mistake. Thank you.
