### ISSUE TITLE
error Run the Pre-trained Model on my data

### ISSUE THREAD

**Issue by hana9090** [liyaguang/DCRNN#40]
after generate train/test for my data which simply contains two columns ( Date, price). I got this information about the training and testing data:
![image](https://user-images.githubusercontent.com/2920520/63649921-90a9cd80-c74c-11e9-9ce2-3b22261c126e.png)

But after running Run the Pre-trained Model, I got the following exception:

> ValueError: Cannot feed value of shape (64, 12, 1, 2) for Tensor 'Test/DCRNN/inputs:0', which has shape '(64, 12, 207, 2)'

![image](https://user-images.githubusercontent.com/2920520/63649930-b59e4080-c74c-11e9-8c22-f764f6a713a9.png)

Is there anything to do to solve this?
Thanks

**Comment by razvanc92** [comment]
I don't think you generated the data right. The data should have shape (N=samples, horizon=12, nodes=207, features=2) it looks like you only generated the data for 1 sensor.

**Comment by hana9090** [comment]
This is my df data:
![image](https://user-images.githubusercontent.com/2920520/63649999-c1d6cd80-c74d-11e9-8415-9b258bf7d58e.png)

I used this script to generate .h5 data.

```
from pandas import (
    DataFrame, HDFStore
)
import pandas as pd
import numpy as np
# creating a HDF5 file
store = HDFStore('data/dataset3.h5')
# adding dataframe to the HDF5 file
store.put('d1', df, format='table') #, data_columns=True)
store.close()
```

From the [link ](https://medium.com/@jerilkuriakose/using-hdf5-with-python-6c5242d08773)you provide.

**Comment by harshgrovr** [comment]
@hana9090 


Hey I am facing the same issue, were you able to resolve?

**Comment by liyaguang** [comment]
Hi @hana9090 , as mentioned by @razvanc92 , the format of the data does not match. 
Besides, the pre-trained model is only expected to do inference on traffic data. Thus, even the format fit, the model will probably not generate a good results for the dataset you mentioned.
You may have to prepare the problem-specific training data, and train the model from scratch.
