### ISSUE TITLE
Original dataset

### ISSUE THREAD

**Issue by razvanc92** [liyaguang/DCRNN#41]
Hello, could you please tell me from where you got the two datasets? I would like to download the raw data (each reading) instead of an 5 minute average. Thank you in advance!

**Comment by Noahprog** [comment]
For PeMS:
http://pems.dot.ca.gov/, create an account and go to clearinghouse. Select "Station Raw", and district 4 (which is the Bay area).
Good luck!

**Comment by yuqirose** [comment]
Caltrans PeMS provides the original dataset.
