### ISSUE TITLE
resource

### ISSUE THREAD

**Issue by ICDI0906** [liyaguang/DCRNN#42]
how to review the map in the Browser by use of Baidu map or google map?

**Comment by liyaguang** [comment]
Hi @ICDI0906 , the detailed map is not available. However, you may visualize the locations of different sensors (data/sensor_graph/graph_sensor_locations.csv) using Baidu/Google map API, e.g., adding [markers](https://developers.google.com/maps/documentation/javascript/markers) to represent a sensor.
