### ISSUE TITLE
Why the distances between two sensors in opposite direction are different? such as the dis from 1 to 2 and from 2 to 1 are different.

### ISSUE THREAD

**Issue by Dukering** [liyaguang/DCRNN#43]

**Comment by liyaguang** [comment]
Hi @Dukering , in general the routes from location 1 to location 2 are different, especially when it involves one-way road, e.g., highway. You may refer to Page 12 in the [slides](http://www-scf.usc.edu/~yaguang/papers/dcrnn_slides.pdf) for more details.

**Comment by Dukering** [comment]
Thanks a lot. Slides are so helpful for some detial !
