### ISSUE TITLE
Question for the cost in /data/sensor_graph/distances_la_2012.csv 

### ISSUE THREAD

**Issue by applewind0** [liyaguang/DCRNN#55]
Thanks for your paper and your code. I've got some problems on the cost in /data/sensor_graph/distances_la_2012.csv. According to paper, I thought that the "cost" should be the distance, but the value I calculated didn't seem like distance, may I know more about the details of the "cost"? Besides, why are the costs not symmetric? 
Thanks for your answer.

**Comment by liyaguang** [comment]
Thanks for the interest of the paper. The cost in the ` /data/sensor_graph/distances_la_2012.csv` indicates the road network distance from the start to the end, which is not symmetric, e.g., some of roads might be one way.

**Comment by applewind0** [comment]
Thanks again!

**Comment by Qofsd** [comment]
hello,i have a question that is how we calculate the cost in "distance_la_2012.csv"?Are you get the cost from the latitude and longitude in graph_sensor_locations.csv?

**Comment by liyaguang** [comment]
As mentioned in the Section 4, the pairwise road network distances between sensors are used as the cost.

To get the cost, we may first map the lat/lon into the road network (with map-matching), and then run the A* algorithm to find the shortest distance between sensor pairs. An alternative way is to use online Map service, which can provide the distance given a source and destination pair.
