### ISSUE TITLE
How are the sensor distance files generated?

### ISSUE THREAD

**Issue by adamthahir** [liyaguang/DCRNN#57]
Hi, I'm looking to run the program on another PeMS dataset, but I could not understand how certain files are generated/obtained. 
I am able to get relevant files from PeMS Clearinghouse. Which I process as needed and then use to generate training data, but I could not follow how to reproduce the steps for the graph construction.

The adjacency matrix generation script requires a sensor_ids_file and a distances_file. The sensors_ids_file I believe I could generate based on the data obtained. I am unsure how to approach the distances_file.

**Comment by yuqirose** [comment]
see answers here https://github.com/chnsh/DCRNN_PyTorch/issues/10#issuecomment-751817157
