### ISSUE TITLE
input of seq2seq

### ISSUE THREAD

**Issue by LeiBAI** [liyaguang/DCRNN#6]
Hi Yaguang,

Thanks for your great work. It give us lots of help. I got one question about the model implementation. In dcrnn_model.py, line 79:
outputs, final_state = legacy_seq2seq.rnn_decoder(labels, enc_state, decoding_cells,
                                                              loop_function=loop_function)
From this sentence, implementation of rnn_decoder and definition of loop function, I think output is induced with the help of label. I know Tensorflow define seq2seq in this way. However, according to the problem definition in prediction, we don't know labels when prediction. Is this a problem?

**Comment by liyaguang** [comment]
Hi LeiBAI,
During the testing, the `labels` variable is not used, see https://github.com/liyaguang/DCRNN/blob/master/model/dcrnn_model.py#L61-L76
Thus, we will get the same prediction results even `labels` is filled with zeros.

**Comment by LeiBAI** [comment]
Yeah, sorry I missed it. Thanks for your answer. Great Work again!
(I think you can close the ticket now)
Lei
