### ISSUE TITLE
Errors may have originated from an input operation.

### ISSUE THREAD

**Issue by wangchaowei666** [liyaguang/DCRNN#62]
Errors may have originated from an input operation.
Input Source operations connected to node Train/DCRNN/DCRNN_SEQ/rnn/rnn/multi_rnn_cell/cell_1_9/dcgru_cell/gates/gates/concat_3:
 Train/DCRNN/DCRNN_SEQ/rnn/rnn/multi_rnn_cell/cell_1_9/dcgru_cell/gates/gates/ExpandDims_3 (defined at D:\code\DCRNN-master\model\dcrnn_cell.py:114)

**Comment by liyaguang** [comment]
Can you provide additional information for debugging purpose?  E.g., python environments,  configs, dataset used etc.

Besides, you may try to have a fresh copy of the data in a new virtual env (e.g., using conda), and see if the error still persist.
